version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: "Asia/Taipei"
  - package-ecosystem: npm
    directories:
      - /
      - /packages/ui
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Asia/Taipei"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      sec-minor-and-patch:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
