// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook'

import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import eslintConfigPrettier from 'eslint-config-prettier'
import tailwind from 'eslint-plugin-tailwindcss'
import importPlugin from 'eslint-plugin-import'

export default tseslint.config(
  {
    ignores: [
      '**/storybook-static',
      '**/dist',
      // Generated by `pnpm icons:generate` - not hand-written source.
      'packages/ui/src/icons/src/**',
    ],
  },
  {
    extends: [
      js.configs.recommended,
      // TODO (low-priority): Find a way to get rid of the following ignore.
      // eslint-disable-next-line import/no-named-as-default-member
      ...tseslint.configs.recommended,
      ...tailwind.configs['flat/recommended'],
      {
        settings: {
          tailwindcss: {
            whitelist: ['cube\\-.*'],
            callees: ['classnames', 'classNames', 'cva', 'twMerge', 'twJoin'],
            config: 'packages/ui/tailwind.config.ts',
            classRegex: '^(\\w+)?[cC]lass(Name)?$',
            // Default cssFiles globs omit dist/build but not storybook-static,
            // whose stale CSS would otherwise "validate" renamed/removed classes.
            cssFiles: [
              '**/*.css',
              '!**/node_modules',
              '!**/.*',
              '!**/dist',
              '!**/build',
              '!**/storybook-static/**',
            ],
          },
        },
      },
    ],
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      'no-console': [
        'error',
        {
          allow: ['error', 'warn'],
        },
      ],
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      'tailwindcss/no-custom-classname': 'error',
      'tailwindcss/classnames-order': 'error',
    },
  },
  {
    // Node-executed build/tooling scripts, as opposed to the browser-run
    // library and Storybook source covered by the block above.
    files: ['**/*.config.{js,ts,mjs,cjs}', '**/scripts/**/*.{js,ts,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.node,
    },
  },
  {
    extends: [
      importPlugin.flatConfigs.recommended,
      importPlugin.flatConfigs.typescript,
    ],
    // eslint-plugin-import's recommended config pins ecmaVersion to 2018
    // with no `files` restriction, silently downgrading it repo-wide since
    // this block has no restriction either. Reassert the real version so
    // newer syntax (e.g. `import.meta`, used by generate-icons.mjs) parses.
    languageOptions: {
      ecmaVersion: 2022,
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          // Both paths are needed: repo-root ESLint uses the first, and the
          // IDE/ESLint cwd under packages/ui uses the second.
          project: ['packages/ui/tsconfig.json', 'tsconfig.json'],
          noWarnOnMultipleProjects: true,
        },
        node: true,
      },
    },
  },
  eslintConfigPrettier,
  // eslint-disable-next-line import/no-named-as-default-member
  storybook.configs['flat/recommended'],
)
