import { execSync } from 'node:child_process'
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const assetsDir = join(packageRoot, 'src/icons/assets')
const outputDir = join(packageRoot, 'src/icons/src')

const toPascalCase = (value: string): string =>
  value
    .replace(/[-_]+([a-zA-Z0-9])/g, (_, char: string) => char.toUpperCase())
    .replace(/^([a-z])/, (_, char: string) => char.toUpperCase())

const getExportName = (relativePath: string): string => {
  const parts = relativePath.split('/')
  const fileName = parts.at(-1) ?? ''
  const componentName = toPascalCase(basename(fileName, extname(fileName)))

  if (parts.length === 1) {
    return componentName
  }

  const category = toPascalCase(parts[0] ?? '')
  return `${category}${componentName}`
}

const collectTsxFiles = async (
  dir: string,
  files: string[] = [],
): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = join(dir, entry.name)

    if (entry.isDirectory()) {
      await collectTsxFiles(fullPath, files)
      continue
    }

    if (entry.name.endsWith('.tsx') && entry.name !== 'index.ts') {
      const posixPath = relative(outputDir, fullPath).split(sep).join('/')
      files.push(posixPath.replace(/\.tsx$/, ''))
    }
  }

  return files
}

await rm(outputDir, { recursive: true, force: true })
await mkdir(outputDir, { recursive: true })

execSync(
  `pnpm exec svgr --config-file svgr.config.js --out-dir "${outputDir}" "${assetsDir}"`,
  {
    cwd: packageRoot,
    stdio: 'inherit',
  },
)

const iconModules = await collectTsxFiles(outputDir)
const exports = iconModules.sort().map((modulePath) => {
  const exportName = getExportName(modulePath)
  return `export { default as ${exportName} } from './${modulePath}'`
})

const indexContent = [
  '// Auto-generated by scripts/generate-icons.ts — do not edit manually.',
  '',
  ...exports,
  '',
].join('\n')

await writeFile(join(outputDir, 'index.ts'), indexContent)

// CLI status output, not debug logging - fine to keep.
// eslint-disable-next-line no-console
console.log(`Generated ${exports.length} icon components.`)
